/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreparacaoRouteImport } from './routes/preparacao'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreparacaoResultadoRouteImport } from './routes/preparacao.resultado'

const PreparacaoRoute = PreparacaoRouteImport.update({
  id: '/preparacao',
  path: '/preparacao',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparacaoResultadoRoute = PreparacaoResultadoRouteImport.update({
  id: '/resultado',
  path: '/resultado',
  getParentRoute: () => PreparacaoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preparacao': typeof PreparacaoRouteWithChildren
  '/preparacao/resultado': typeof PreparacaoResultadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preparacao': typeof PreparacaoRouteWithChildren
  '/preparacao/resultado': typeof PreparacaoResultadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/preparacao': typeof PreparacaoRouteWithChildren
  '/preparacao/resultado': typeof PreparacaoResultadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/preparacao' | '/preparacao/resultado'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/preparacao' | '/preparacao/resultado'
  id: '__root__' | '/' | '/preparacao' | '/preparacao/resultado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PreparacaoRoute: typeof PreparacaoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preparacao': {
      id: '/preparacao'
      path: '/preparacao'
      fullPath: '/preparacao'
      preLoaderRoute: typeof PreparacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparacao/resultado': {
      id: '/preparacao/resultado'
      path: '/resultado'
      fullPath: '/preparacao/resultado'
      preLoaderRoute: typeof PreparacaoResultadoRouteImport
      parentRoute: typeof PreparacaoRoute
    }
  }
}

interface PreparacaoRouteChildren {
  PreparacaoResultadoRoute: typeof PreparacaoResultadoRoute
}

const PreparacaoRouteChildren: PreparacaoRouteChildren = {
  PreparacaoResultadoRoute: PreparacaoResultadoRoute,
}

const PreparacaoRouteWithChildren = PreparacaoRoute._addFileChildren(
  PreparacaoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PreparacaoRoute: PreparacaoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
