/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistIdRouteImport } from './routes/checklist.$id'
import { Route as ChecklistIdResumoRouteImport } from './routes/checklist.$id.resumo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistIdRoute = ChecklistIdRouteImport.update({
  id: '/checklist/$id',
  path: '/checklist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistIdResumoRoute = ChecklistIdResumoRouteImport.update({
  id: '/resumo',
  path: '/resumo',
  getParentRoute: () => ChecklistIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklist/$id': typeof ChecklistIdRouteWithChildren
  '/checklist/$id/resumo': typeof ChecklistIdResumoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklist/$id': typeof ChecklistIdRouteWithChildren
  '/checklist/$id/resumo': typeof ChecklistIdResumoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklist/$id': typeof ChecklistIdRouteWithChildren
  '/checklist/$id/resumo': typeof ChecklistIdResumoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/checklist/$id' | '/checklist/$id/resumo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/checklist/$id' | '/checklist/$id/resumo'
  id: '__root__' | '/' | '/checklist/$id' | '/checklist/$id/resumo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistIdRoute: typeof ChecklistIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist/$id': {
      id: '/checklist/$id'
      path: '/checklist/$id'
      fullPath: '/checklist/$id'
      preLoaderRoute: typeof ChecklistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist/$id/resumo': {
      id: '/checklist/$id/resumo'
      path: '/resumo'
      fullPath: '/checklist/$id/resumo'
      preLoaderRoute: typeof ChecklistIdResumoRouteImport
      parentRoute: typeof ChecklistIdRoute
    }
  }
}

interface ChecklistIdRouteChildren {
  ChecklistIdResumoRoute: typeof ChecklistIdResumoRoute
}

const ChecklistIdRouteChildren: ChecklistIdRouteChildren = {
  ChecklistIdResumoRoute: ChecklistIdResumoRoute,
}

const ChecklistIdRouteWithChildren = ChecklistIdRoute._addFileChildren(
  ChecklistIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistIdRoute: ChecklistIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
